website/Main/urls.py
from django.conf.urls import *

urlpatterns = patterns('Main.views',
        url(r'home','Home'),
        url(r'article_add/$','ArticleNew'),
        url(r'article_(\d+)/$','ArticleDetail'),
        url(r'^(\w+)/$','ArticleList'),
        url(r'^user/',include('User.urls')),
        url(r'^$','Home'),
)

website/main/urls.py
from django.conf.urls import *

urlpatterns = patterns('main.views',
        url(r'home','Home'),
        url(r'article_add/$','ArticleNew'),
        url(r'article_(\d+)/$','ArticleDetail'),
        url(r'^(\w+)/$','ArticleList'),
        url(r'^user/',include('users.urls')),
        url(r'^$','Home'),
)

website/Main/models.py
#coding=utf-8
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

from django.db import models
from User.models import User

import hashlib

#------ 新闻模块 -------

class Category(models.Model):
    name = models.CharField(max_length=32,unique=True)
    chinese_name = models.CharField(max_length=32,unique=True)
    father_category = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=64)
    summary = models.CharField(max_length=258,blank=True,null=True)
    content =models.TextField()
    viewCount = models.IntegerField(default=0)
    commentCount = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User)
    category = models.ForeignKey('Category')

    def __unicode__(self):
        return self.title

#------ 评论模块 -------

class Comment(models.Model):
    content = models.CharField(max_length=256)
    create_at = models.DateTimeField(auto_now_add=True)
    vote = models.IntegerField(default=0)
    author = models.ForeignKey(User)
    article = models.ForeignKey('Article')
    
    def add_vote(self):
        self.vote += 1
        self.save()

    def __unicode__(self):
        return self.author.username

website/main/models.py
#coding=utf-8
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

from django.db import models
from users.models import User

import hashlib

#------ 新闻模块 -------

class Category(models.Model):
    name = models.CharField(max_length=32,unique=True)
    chinese_name = models.CharField(max_length=32,unique=True)
    father_category = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=64)
    summary = models.CharField(max_length=258,blank=True,null=True)
    content =models.TextField()
    viewCount = models.IntegerField(default=0)
    commentCount = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User)
    category = models.ForeignKey('Category')

    def __unicode__(self):
        return self.title

#------ 评论模块 -------

class Comment(models.Model):
    content = models.CharField(max_length=256)
    create_at = models.DateTimeField(auto_now_add=True)
    vote = models.IntegerField(default=0)
    author = models.ForeignKey(User)
    article = models.ForeignKey('Article')
    
    def add_vote(self):
        self.vote += 1
        self.save()

    def __unicode__(self):
        return self.author.username

website/Main/views.py
#coding=utf-8

from django.template.loader import get_template
from django.http import HttpResponse,HttpResponseRedirect
from PIL import Image,ImageDraw,ImageFont

from Main.models import *

def Home(request):	
	catList = Category.objects.filter(father_category=0).order_by('id')
	articleList = Article.objects.order_by("create_at")

	context = {
			'article_list':articleList,
			'cat_list':catList,
		}
	template = get_template("main/home.html")
	html = template.render(context,request)	
	return HttpResponse(html)

def ArticleList(request,actType="xx"):
	try:
		getCategory = Category.objects.get(name = actType)
	except Category.DoesNotExist:
		return HttpResponseRedirect("error404")
	articleList = Article.objects.filter(category = getCategory).order_by("create_at")
	context = {
		"select_category":getCategory,
		"article_list":articleList
	}
	template = get_template("main/article_list.html")
	html = template.render(context,request)	
	return HttpResponse(html)

def ArticleDetail(request,artID=None):
	try:
		article = Article.objects.get(id = artID)
	except Article.DoesNotExist:
		return HttpResponseRedirect("error404")
	context = {
		"article":article,
	}
	template = get_template("main/article_detail.html")
	html = template.render(context,request)	
	return HttpResponse(html)

def ArticleNew(request):
	context = {}
	template = get_template("main/new.html")
	html = template.render(context,request)	
	return HttpResponse(html)

website/main/views.py
#coding=utf-8

from django.template.loader import get_template
from django.http import HttpResponse,HttpResponseRedirect
from PIL import Image,ImageDraw,ImageFont

from users.views import login_required
from users.functions import getSession
from main.models import *

def Home(request):
    catList = Category.objects.filter(father_category=0).order_by('id')
    articleList = Article.objects.order_by("create_at")
    
    user = getSession(request)
    context = {
            'article_list':articleList,
            'cat_list':catList,
            'user':user,
        }
    template = get_template("main/home.html")
    html = template.render(context,request) 
    return HttpResponse(html)

def ArticleList(request,actType="xx"):
    try:
        getCategory = Category.objects.get(name = actType)
    except Category.DoesNotExist:
        return HttpResponseRedirect("error404")
    articleList = Article.objects.filter(category = getCategory).order_by("create_at")
    user = getSession(request)
    context = {
            "select_category":getCategory,
            "article_list":articleList,
            'user':user,
    }
    template = get_template("main/article_list.html")
    html = template.render(context,request) 
    return HttpResponse(html)

def ArticleDetail(request,artID=None):
    try:
        article = Article.objects.get(id = artID)
    except Article.DoesNotExist:
        return HttpResponseRedirect("error404")
        
    user = getSession(request)
    context = {
            "article":article,
            'user':user,
    }

    template = get_template("main/article_detail.html")
    html = template.render(context,request) 
    return HttpResponse(html)

@login_required
def ArticleNew(request):
    user = getSession(request)
    context = { 
        "user":user
        }
    template = get_template("main/new.html")
    html = template.render(context,request) 
    return HttpResponse(html)

templates/main/detial.html
{% extends "bbs/index.html" %}
{% block page-content %}
	<h2>{{ bbs_obj.title }}</h2>
	<div style="font-size:25px"><span>作者:</span><a href="/bbs/Uinfo/{{ bbs_obj.author }}"/><em>{{ bbs_obj.author }} </em></a></div>
	<div style="font-size:20px"> {{ bbs_obj.content|safe }} </div>
	<hr>
	<span class="glyphicon glyphicon-comment"></span>
	<span id="com_count">{{ bbs_obj.comments }}</span>
	<span class="pull-right">{{ bbs_obj.updated_at }}</span>
	<hr>
	{% if user.is_authenticated %}
		<form class='form-horizontal' role='form' method="post">
			<textarea class="form-control" id="comment_content" rows="3"></textarea>
			<div style="height:20px;margin:5px">
				<button id="submit_bt" class='btn btn-md btn-primary pull-right ' type='button'>提交评论</button>
			</div>
		</form>
	{% else %}
		<p align="center"><em> 请先<a href="/bbs/login/">登录</a> 再发表评论！</em></p>
	{% endif %}
	<hr id="target_hr">

	{% if comm_obj_list %}
	{% for comment in comm_obj_list reversed %}
	<div>
		<span>{{ comment.Ctime|date:"Y/m/d H:i" }}</span>
		<span><a href="/bbs/Uinfo/{{ comment.author }}/">{{ comment.author }}</a></span>
	</div>
		<p>{{ comment.content }}</p>
	<hr> 
	{% endfor %}
	{% endif %}
	<nav>
		<ul class="pagination">
			{% ifequal Comm_cur_page 1 %}
				<li class="disabled"><span style="background-color:#ECECEC;">&laquo;</span></li>
			{% else %}
				<li><a href="/bbs/{{ Cat_obj.name }}/{{ bbs_obj.id }}/?Cp={{ Pre_cpage }}">&laquo;</a></li>
			{% endifequal %}
			{% for page in pagelist %}
				{% ifequal page Comm_cur_page %}
				<li class="active"><a href="/bbs/{{ Cat_obj.name }}/{{ bbs_obj.id }}/?Cp={{ page }}">{{ page }}</a></li>
				{% else %}
				<li><a href="/bbs/{{ Cat_obj.name }}/{{ bbs_obj.id }}/?Cp={{ page }}">{{ page }}</a></li>
				{% endifequal %}
			{% endfor %}
			{% ifequal Comm_cur_page allpage %}
				<li class="disabled" ><span style="background-color:#ECECEC;">&raquo;</span></li>
			{% else %}
				<li><a href="/bbs/{{ Cat_obj.name }}/{{ bbs_obj.id }}/?Cp={{ Next_cpage }}">&raquo;</a></li>
			{% endifequal %}						
		</ul>
	</nav>
{% if user.is_authenticated %}
<script type="text/javascript">
 $(function (){
        $("#submit_bt").bind("click", function () {
			var comm_content=$("#comment_content");
			var target=$("#target_hr");
			var com_count=$("#com_count");
			if(comm_content.val() == ""){
				alert("提交的评论不能为空！")
			}
			else{
            $.ajax({
                type:"post",
				dataType:"json",
				url:"/bbs/post_comm/",
                data:{ 
                    "Cat_name":"{{ Cat_obj.name }}", 
                    "bbs_id":"{{ bbs_obj.id }}", 
					"comment_content":comm_content.val(),
                    }, 
				success: function (data) {    
					if(data != ""){
						html="<div>";
						html+="<span>" + data.Com_ctime + "</span>&nbsp;";
						html+="<span><a href='/bbs/Uinfo/" + data.Com_author + "/'>" + data.Com_author + "</a></span>";
						html+="</div>";
						html+="<p>" + data.Com_content + "</p>";
						html+="<hr>"
						target.after(html);
						com_count.text(data.Com_counts);
						}
					}
				});
			}
        });
    });
 </script>
 {% endif %}
{% endblock %}

templates/main/error.html
{% extends 'bbs/index.html' %}
{% block page-content %}
<h2 style="color:red">错误请求</h2>
<p><span id="showTime"style="color:green">3</span> 秒后自动跳转到 <a href='/bbs/'>首页</a></p>




<script type="text/javascript">
	$(function(){
	var timer;
	var count=4;
	function auto_jump1(){
		timer = window.setInterval(auto_jump2,1000)
	}
	function auto_jump2(){
		count--;
		$("#showTime").text(count);
		if(count == 0){
			window.clearInterval(timer);
			window.location.href='/bbs/';
		}
	}
	auto_jump1();
	
	
	
	
	
	
	});
</script>
{% endblock %}

templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}

{% block page-content %}
    <div class="col-md-9">
        {% for bbs in bbs_list %}
            <a href="/bbs/{{ bbs.category.name }}/{{ bbs.id }}/"><h3>{{ bbs.title }}</h3></a>
            <br>
            {{ bbs.summary }}
            <div>
                <p style="margin-top:10px;font-size:15px">
                <span class="glyphicon glyphicon-tag"></span>
                <a href="/bbs/{{ bbs.category.name }}/">{{ bbs.category.chinese_name }}</a>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <span class="glyphicon glyphicon-edit"></span>
                <a href="/bbs/Uinfo/{{ bbs.author }}/">{{ bbs.author }}</a>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <span class="glyphicon glyphicon-comment"></span>
                <span>{{ bbs.comments }}</span>
                <span class="pull-right">{{ bbs.updated_at|date:"Y/m/d H:i" }}</span>
                </p>
            </div>
            <hr>
        {% endfor %}
    </div>
    <div class="col-md-3" style="background-color:white;">
        <h3>帖子总数: {{ Total_tips }} </h3>
        <a class="btn btn-success btn-lg" href="/bbs/article_add/">新帖</a>
    </div>
{% endblock %}
    
{% block js %}
    <script type="text/javascript" src={% static "bbs/js/tinymce/tinymce.min.js" %}></script>
    <script type="text/javascript">
    tinymce.init({
        selector: "textarea#id_content",
        theme: "modern",
        //width: 300,
        //height: 300,
        language:'zh_CN',
        plugins: [
             "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
             "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
             "save table contextmenu directionality emoticons template paste textcolor"
       ],
       //content_css: "/Templates/bbs/js/tinymce/css/content.css",
       toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons", 
       style_formats: [
            {title: 'Bold text', inline: 'b'},
            {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
            {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
            {title: 'Example 1', inline: 'span', classes: 'example1'},
            {title: 'Example 2', inline: 'span', classes: 'example2'},
            {title: 'Table styles'},
            {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
        ]
     }); 
    </script>
{% endblock %}

templates/main/modify_tip.html
{% extends 'bbs/index.html' %}
{% block userinfo %}
	<ul class="nav navbar-nav navbar-left">
		<li><a href="/bbs/Uinfo/{{ Gusername }}/">用户信息</a></li>
		<li class="active"><a href="/bbs/Uinfo/{{ Gusername }}/MyTips/">用户帖子</a></li>
		<li><a href="/bbs/Uinfo/{{ Gusername }}/MyComments/">用户评论</a></li>
	</ul>
{% endblock %}
{% block page-content %}
	{% if  not user.is_authenticated %}
		<p>请<a href="/bbs/login/">登录</a> ，在发帖,没有账号请先<a href="/bbs/register/">注册 </a></p>
	{% else %}
	<div class="col-md-12">
		<form class="form-horizontal" role="form">
		{% csrf_token %}
			<div class="form-group">
				<label for="inputtitle" class="col-sm-1 control-label">标题</label>
				<div class="col-sm-11" >
					<input class="from-control" name="username" style="width:50%;" id="id_title" value="{{ BBS_obj.title }}"/>
					<span id="sh_msg1" style="margin-left:5px;font-size:20px;"></span>
				</div>
					<div style='height:10px;clear:both;display:block'></div>
				<label for="input-summary" class="col-sm-1 control-label">类型</label>
				<div class="col-sm-11" >
					<select id="id_cate" class="form-control" style="width:20%;">
					{% for cat in cat_list %}
						{% ifnotequal cat.name "Home" %}
							{% ifequal cat.name BBS_obj.category.name %}
								<option value="{{ cat.name }}" selected="selected">{{ cat.chinese_name }}</option>
							{% else %}
								<option value="{{ cat.name }}">{{ cat.chinese_name }}</option>
							{% endifequal %}
						{% endifnotequal %}
					{% endfor %}
					</select>
				</div>
					<div style='height:10px;clear:both;display:block'></div>
				<label for="input-summary" class="col-sm-1 control-label">概要</label>
				<div class="col-sm-11" >
					<input class="from-control" name="username" style="width:50%;" id="id_summary" value="{{ BBS_obj.summary }}"/>
					<span id="sh_msg2" style="margin-left:5px;font-size:20px;"></span>
				</div>
					<div style='height:10px;clear:both;display:block'></div>
				<label for="input content" class="col-sm-1 control-label">正文</label>
				<div class="col-sm-11" >
					<textarea id="id_content" name="signature" class="form-control"   style="height:300px;" >{{ BBS_obj.content }}</textarea>
				</div>
				<div class="col-sm-offset-1 col-sm-11" style="height:30px;">
					<span id="sh_msg3" style="margin-left:5px;font-size:20px;"></span>
				</div>
				<div class="col-sm-12">
					<button id="sub_tips" class="btn btn-success btn-lg pull-right" type="button"> 确认修改</button>
				</div>
			</div>
		</form> 
	</div>
	
	<script type="text/javascript">
	$(function(){
		$("#sub_tips").bind("click", function () {
			var title=$("#id_title");
			var summary=$("#id_summary");
			var content=tinyMCE.get('id_content').getContent();
			var cate=$("#id_cate");
			var msg1=$("#sh_msg1");
			var msg2=$("#sh_msg2");
			var msg3=$("#sh_msg3");
			if(title.val()==""){
				html="Title can not be empty !"
				msg1.text(html);
				msg1.css('color','red');
			}
			else if(summary.val()==""){
				html="Summary can not be empty !"
				msg2.text(html);
				msg2.css('color','red');
			}
			else if(content.length==0){
				html="Content can not be empty !"
				msg3.text(html);
				msg3.css('color','red');
			}
			else if(title.val().length>50){
				html="More then 30 letters in this title!"
				msg1.text(html);
				msg1.css('color','red');
				}
			else if(summary.val().length>100){
				html="More then 50 letters in this summary!"
				msg2.text(html);
				msg2.css('color','red');				
				}
			else{
            $.ajax({
                type:"post",
				dataType:"json",
				url:"/bbs/post_tip/",
                data:{ 
					"bbs_id":"{{ BBS_obj.id }}",
                    "username":"{{ user.username }}", 
					"title":title.val(),
					"category":escape(cate.val()),
					"summary":summary.val(),
					"content":content,
                    }, 
				success: function (data) {    
						if(data.result=="failed"){
							msg1.empty();
							msg2.empty();
							msg3.empty();
							var html="failed to create tip";
							msg3.text(html);
							msg3.css('color','red');
						}
						else if(data.result=="success"){
							window.location.href="/bbs/"+cate.val()+"/"+{{ BBS_obj.id }};
						}
					}
				});
			}
		});
	});
	</script>
	{% endif %}
{% endblock %}

templates/main/mycomments.html
{% extends 'bbs/index.html' %}
{% block userinfo %}
	<ul class="nav navbar-nav navbar-left">
		<li><a href="/bbs/Uinfo/{{ Gusername }}/">用户信息</a></li>
		<li><a href="/bbs/Uinfo/{{ Gusername }}/MyTips/">用户帖子</a></li>
		<li class="active"><a href="/bbs/Uinfo/{{ Gusername }}/MyComments/">用户评论</a></li>
	</ul>
{% endblock %}
{% block page-content %}
	{% if  not user.is_authenticated %}
		<p>请先<a href="/bbs/login/">登录</a>再查看用户信息 ! ,没有账号，请先<a href="/bbs/register">注册</a></p>
	{% else %}
		<div class="col-md-12">
		<table class="table">
			<thead>
				<tr>
					<th>评论内容</th>
					<th>帖子标题</th>
					<th>评论生成时间</th>
					{% ifequal user.username Gusername %}
						<th>评论管理</th>
					{% endifequal %}
				</tr>
			</thead>
			<tbody>
			{% ifequal user.username Gusername %}
				{% for comment in Comm_obj_list %}	
				<tr>
					<td>{{ comment.content|truncatewords:"10" }}</td>
					<td><a href='/bbs/{{ comment.bbs.category.name }}/{{ comment.bbs.id }}/'>{{ comment.bbs.title|truncatewords:"20" }}</a></td>
					<td>{{ comment.Ctime|date:"Y/m/d H:i" }}</td>
					<td>
						<button type="button" class="btn btn-danger btn-sm" value="{{ comment.id }}" value="{{ comment.id }}"><i class="glyphicon glyphicon-trash icon-white"></i>  删除</button>
					</td>
				</tr>
				{% endfor %} 
			{% else %}
				{% for comment in Comm_obj_list %}	
				<tr>
					<td>{{ comment.content|truncatewords:"10" }}</td>
					<td><a href='/bbs/{{ comment.bbs.category.name }}/{{ comment.bbs.id }}/'>{{ comment.bbs.title|truncatewords:"20" }}</a></td>
					<td>{{ comment.Ctime|date:"Y/m/d H:i" }}</td>
				</tr>
				{% endfor %}
			{% endifequal %}			
			</tbody>
		</table>
		</div>
	{% endif %}
{% if user.is_authenticated %}
{% ifequal user.username Gusername %}
 <script type="text/javascript">
    $(function (){
        $(".btn-danger").bind("click", function () {
			$.ajax({
                type:"post",
				dataType:"json",
				url:"/bbs/comments_modify/",
                data:{ 
					"Gusername":"{{ Gusername }}",
                    "Comm_id":escape(this.value),      
                    }, 
				success: function (data) {    
					if(data != ""){
					window.location.reload();
					}
                }
            });
        });
    });
 </script>
 {% endifequal %}
 {% endif %}
 {% endblock %}

templates/main/mytips.html
{% extends 'bbs/index.html' %}
{% block userinfo %}
	<ul class="nav navbar-nav navbar-left">
		<li><a href="/bbs/Uinfo/{{ Gusername }}/">用户信息</a></li>
		<li class="active"><a href="/bbs/Uinfo/{{ Gusername }}/MyTips/">用户帖子</a></li>
		<li><a href="/bbs/Uinfo/{{ Gusername }}/MyComments/">用户评论</a></li>
	</ul>
{% endblock %}
{% block page-content %}
	{% if  not user.is_authenticated %}
		<p>请先<a href="/bbs/login/">登陆</a>再查看用户信息！没有账号，请先<a href="/bbs/register">注册</a></p>
	{% else %}
		<div class="col-md-12">
		<table class="table">
			<thead>
				<tr>
					<th>标题</th>
					<th>评论数</th>
					<th>类型</th>
					<th>创建时间</th>
					<th>最后更新时间</th>
					{% ifequal user.username Gusername %}
						<th>帖子管理</th>
					{% endifequal %}
				</tr>
			</thead>
			<tbody>
			{% ifequal user.username Gusername %}
				{% for bbs in BBS_obj_list %}	
				<tr>
					<td> <a href="/bbs/{{ bbs.category.name }}/{{ bbs.id }}/">{{ bbs.title }}</a></td>
					<td>{{ bbs.comments }}</td>
					<td>{{ bbs.category.chinese_name }}</td>
					<td>{{ bbs.created_at|date }}</td>
					<td>{{ bbs.updated_at|date }}</td>
					<td>
						<a class="btn btn-warning btn-sm" href="/bbs/Uinfo/{{ user.username }}/MyTips/{{ bbs.id }}/"><i class="glyphicon glyphicon-pencil icon-white"></i>  编辑</a>&nbsp;
						<button type="button" class="btn btn-danger btn-sm" value="{{ bbs.id }}"><i class="glyphicon glyphicon-trash icon-white"></i>  删除</button>
					</td>
				</tr>
				{% endfor %} 
			{% else %}
				{% for bbs in BBS_obj_list %}	
				<tr>
					<td> <a href="/bbs/{{ bbs.category.name }}/{{ bbs.id }}/">{{ bbs.title }}</a></td>
					<td>{{ bbs.comments }}</td>
					<td>{{ bbs.category.name }}</td>
					<td>{{ bbs.created_at|date }}</td>
					<td>{{ bbs.updated_at|date }}</td>
				</tr>
				{% endfor %}
			{% endifequal %}			
			</tbody>
		</table>
		</div>
	{% endif %}
{% if user.is_authenticated %}
{% ifequal user.username Gusername %}
 <script type="text/javascript">
    $(function (){
        $(".btn-danger").bind("click", function () {
			$.ajax({
                type:"post",
				dataType:"json",
				url:"/bbs/tips_modify/",
                data:{ 
					"Gusername":"{{ Gusername }}",
                    "modify_type":"bbs_del", 
                    "bbs_id":escape(this.value),      
                    }, 
				success: function (data) {    
					if(data.resulte=="success"){
					window.location.reload();
					}
					else{
						alert("帖子删除失败！");
					}
                }
            });
        });
		
    });
 </script>
 {% endifequal %}
 {% endif %}
{% endblock %}

templates/main/new.html
{% extends 'user/base.html' %}
{% load static %}

{% block page-content %}
	<div class="col-md-12">
		<form class="form-horizontal" role="form">
		{% csrf_token %}
			<div class="form-group">
				<label for="inputtitle" class="col-sm-1 control-label">标题</label>
				<div class="col-sm-11" >
					<input class="from-control" name="username" style="width:50%;" id="id_title" />
					<span id="sh_msg1" style="margin-left:5px;font-size:20px;"></span>
				</div>
					<div style='height:10px;clear:both;display:block'></div>
				<label for="input-summary" class="col-sm-1 control-label">类型</label>
				<div class="col-sm-11" >
					<select id="id_cate" class="form-control" style="width:20%;">
					{% for cat in cat_list %}
						{% ifnotequal cat.name "Home" %}
							<option value="{{ cat.name }}">{{ cat.chinese_name }}</option>
						{% endifnotequal %}
					{% endfor %}
					</select>
				</div>
					<div style='height:10px;clear:both;display:block'></div>
				<label for="input-summary" class="col-sm-1 control-label">概要</label>
				<div class="col-sm-11" >
					<input class="from-control" name="username" style="width:50%;" id="id_summary" />
					<span id="sh_msg2" style="margin-left:5px;font-size:20px;"></span>
				</div>
					<div style='height:10px;clear:both;display:block'></div>
				<label for="input content" class="col-sm-1 control-label">正文</label>
				<div class="col-sm-11" >
					<textarea id="id_content" name="signature" class="form-control"   style="height:300px;" ></textarea>
				</div>
				<div class="col-sm-offset-1 col-sm-11" style="height:30px;">
					<span id="sh_msg3" style="margin-left:5px;font-size:20px;"></span>
				</div>
				<div class="col-sm-12">
				<button id="sub_tips" class="btn btn-success btn-lg pull-right" type="button"/>发布</button>
				</div>
			</div>
		</form> 
	</div>
{% endblock %}

{% block js %}
	<script type="text/javascript">
	$(function(){
		$("#sub_tips").bind("click", function () {
			var title=$("#id_title");
			var summary=$("#id_summary");
			var content=tinyMCE.get('id_content').getContent();
			var cate=$("#id_cate");
			var msg1=$("#sh_msg1");
			var msg2=$("#sh_msg2");
			var msg3=$("#sh_msg3");
			if(title.val()==""){
				html="Title can not be empty !"
				msg1.text(html);
				msg1.css('color','red');
			}
			else if(summary.val()==""){
				html="Summary can not be empty !"
				msg2.text(html);
				msg2.css('color','red');
			}
			else if(content.length==0){
				html="Content can not be empty !"
				msg3.text(html);
				msg3.css('color','red');
			}
			else if(title.val().length>50){
				html="More then 30 letters in this title!"
				msg1.text(html);
				msg1.css('color','red');
				}
			else if(summary.val().length>100){
				html="More then 50 letters in this summary!"
				msg2.text(html);
				msg2.css('color','red');				
				}
			else{
            $.ajax({
                type:"post",
				dataType:"json",
				url:"/bbs/post_tip/",
                data:{ 
                    "username":"{{ user.username }}", 
					"title":title.val(),
					"category":escape(cate.val()),
					"summary":summary.val(),
					"content":content,
                    }, 
				success: function (data) {    
						if(data.result=="failed"){
							msg1.empty();
							msg2.empty();
							msg3.empty();
							var html="failed to create tip";
							msg3.text(html);
							msg3.css('color','red');
						}
						else if(data.result=="success"){
							window.location.href="/bbs/"+cate.val()+"/"+data.id;
						}
					}
				});
			}
		});
	});
	</script>
{% endblock %}