website/Main/urls.py
from django.conf.urls import *

urlpatterns = patterns('Main.views',
        url(r'home','Home'),
        url(r'article_add/$','ArticleNew'),
        url(r'article_(\d+)/$','ArticleDetail'),
        url(r'^(\w+)/$','ArticleList'),
        url(r'^user/',include('User.urls')),
        url(r'^$','Home'),
)

website/User/urls.py
from django.conf.urls import *

urlpatterns = patterns('User.views',
	url(r'^login/$','Login'),
	url(r'^register/$','Register'),
	url(r'^active/$','UserActive'),

	#---- ajax ----
	url(r'^get_chaptcha/$','getChaptcha'),
	url(r'^uname_available/$','unameAvailableCheck'),
	url(r'^post_register/$','postRegister'),
	url(r'^post_login/$','postLogin'),
	url(r'^check_chapcha/$','checkChapcha'),
)

website/users/urls.py
from django.conf.urls import *

urlpatterns = patterns('users.views',
	url(r'^login/$','Login'),
	url(r'^logout/$','Logout'),
	url(r'^register/$','Register'),
	url(r'^active/$','userActive'),

	#---- ajax ----
	url(r'^get_chaptcha/$','getChaptcha'),
	url(r'^uname_available/$','unameAvailableCheck'),
	url(r'^post_register/$','postRegister'),
	url(r'^post_login/$','postLogin'),
	url(r'^check_chapcha/$','checkChapcha'),
)

website/User/models.py
#coding=utf-8
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

from django.db import models
from django.core.mail import send_mail
from django.template.loader import render_to_string

import hashlib
import time

#------ 用户模块 -------

class User(models.Model):
    username = models.CharField(max_length=64, unique=True)
    passwd = models.CharField(max_length=128)
    email = models.CharField(max_length=128)
    signature = models.CharField(max_length=128,default='This guy is very lazy to leave anything here')
    photo = models.CharField(max_length=256, default="default.png")
    is_login = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    salt = models.CharField(max_length=256)
    token = models.CharField(max_length=64,blank=True)
    
    def genSalt(self):
        m1 = hashlib.md5()
        m1.update(str(time.time()))
        return m1.hexdigest()[:10]

    def e1(self,str_):
        m1 = hashlib.md5()
        m1.update(self.username + str_)
        return m1.hexdigest()

    def encrypt(self,str_):
        s1 = hashlib.sha256()
        s1.update(str_)
        return s1.hexdigest()

    def set_token(self):
        self.token = self.genSalt()
        self.save()

    def set_login(self):
        self.is_login = True
        self.save()

    def set_logout(self):
        self.is_login = False
        self.save()

    def set_active(self):
        self.active = True
        self.save()

    def set_password(self,str_):
        self.salt = self.genSalt()
        self.passwd = self.encrypt(self.e1(str_) + self.salt)
        self.save()

    def check_password(self,str_):
        return self.passwd == self.encrypt(self.e1(str_) + self.salt)

    def sendMail(self,msgType,host="172.16.36.39"):
        email_subject =""
        email_body =""
        self.set_token()

        if msgType == "register":
            email_subject = "Welcome join in Chouti"
            email_body = render_to_string("user/email_signup.txt",{"username":self.username,"token":self.token,"host":host})
        elif msgType == "reset":
            email_subject = "Reset your password for Chouti"
            email_body = render_to_string("user/email_reset.txt",{"username":self.username,"token":self.token,"host":host})
        send_mail(email_subject, email_body, 'P_cngb_db@genomics.cn',[self.email,], fail_silently=False)

    def __unicode__(self):
        return self.username

website/User/forms.py
#coding=utf-8

from User.models import User
import re

class UserForm(object):
    def __init__(self,request):
        self.username = request.POST.get("username","").strip()
        self.password = request.POST.get("password","").strip()
        self.email = request.POST.get("email","").strip()
        self.signature = request.POST.get("signature","").strip()
        self.error = ""

    def clean_username(self):
        re1 = re.compile(r'[^\w\u4e00-\u9fa5]+')
        flag = False

        try:
            self.username = self.username.encode("utf-8")
        except UnicodeDecodeError:
            self.error = u"用户名编码错误"
        else:
            if self.username:
                if re1.match(self.username):
                    self.error = u"非法的用户名"
                else:
                    flag = True
            else:
                self.error = u"用户名不能为空"
        return flag

    def clean_password(self):
        re1 = re.compile(r'^[a-zA-Z0-9_]+$')
        flag = False
        if self.password:
            if re1.match(self.password):
                flag = True
            else:
                self.error = u"非法的密码"
        else:
            self.error = u"密码不能为空"
        return flag

    def clean_email(self):
        re1 = re.compile(r'^[a-zA-Z0-9_]{3,15}@[a-zA-Z0-9]{2,10}\.[a-z]{2,3}$')
        flag = False
        if self.email:
            if re1.match(self.email):
                flag = True
            else:
                self.error = u"非法的邮箱地址"
        else:
            self.error = u"邮箱不能为空"
        return flag

    def is_valid(self):
        key = True
        check_all = [
            self.clean_username(),
            self.clean_password(),
            self.clean_email(),
        ]

        for item in check_all:
            if not item:
                key = False
                break
        return key

    def save(self):
        user = User()
        user.username = self.username
        user.set_password(self.password)
        user.email = self.email
        if self.signature:
            user.signature = self.signature
        user.save()
        return user

website/users/forms.py
#coding=utf-8

from users.models import User
import re

class userForm(object):
    def __init__(self,request):
        self.username = request.POST.get("username","").strip()
        self.password = request.POST.get("password","").strip()
        self.email = request.POST.get("email","").strip()
        self.signature = request.POST.get("signature","").strip()
        self.error = ""

    def clean_username(self):
        re1 = re.compile(r'[^\w\u4e00-\u9fa5]+')
        flag = False

        try:
            self.username = self.username.encode("utf-8")
        except UnicodeDecodeError:
            self.error = u"用户名编码错误"
        else:
            if self.username:
                if re1.match(self.username):
                    self.error = u"非法的用户名"
                else:
                    flag = True
            else:
                self.error = u"用户名不能为空"
        return flag

    def clean_password(self):
        re1 = re.compile(r'^[a-zA-Z0-9_]+$')
        flag = False
        if self.password:
            if re1.match(self.password):
                flag = True
            else:
                self.error = u"非法的密码"
        else:
            self.error = u"密码不能为空"
        return flag

    def clean_email(self):
        re1 = re.compile(r'^[a-zA-Z0-9_]{3,15}@[a-zA-Z0-9]{2,10}\.[a-z]{2,3}$')
        flag = False
        if self.email:
            if re1.match(self.email):
                flag = True
            else:
                self.error = u"非法的邮箱地址"
        else:
            self.error = u"邮箱不能为空"
        return flag

    def is_valid(self):
        key = True
        check_all = [
            self.clean_username(),
            self.clean_password(),
            self.clean_email(),
        ]

        for item in check_all:
            if not item:
                key = False
                break
        return key

    def save(self):
        user = User()
        user.username = self.username
        user.set_password(self.password)
        user.email = self.email
        if self.signature:
            user.signature = self.signature
        user.save()
        return user

website/User/views.py
#coding=utf-8

from django.template.loader import get_template
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse

from Main.models import Category
from User.forms import UserForm
from User.models import *
from functions import *

def Login(request):
	'''
	显示登陆页面
	'''
	catList = Category.objects.order_by('id')
	context = {
		'cat_list':catList,
		}
	template = get_template("user/login.html")
	html = template.render(context,request)
	return HttpResponse(html)

def Register(request):
	'''
	显示注册页面
	'''
	catList = Category.objects.order_by('id')
	context = {
		'cat_list':catList,
		}
	template = get_template("user/register.html")
	html = template.render(context,request)
	return HttpResponse(html)

def UserActive(request):
	'''
	账户激活
	'''
	email_token = str(request.GET.get('token','').strip())
	catList = Category.objects.order_by('id')
	result = "success"
	context = {}
	context["cat_list"] = catList

	try:
		user = User.objects.get(token=email_token)
	except:
		context["get_token"] = False
	else:
		context["get_token"] = True
		if user.active:
			context["info"] = u"该账户已激活"
		else:
			user.set_active()
			context["info"] = u"账户激活成功"
	template = get_template("user/active.html")
	html = template.render(context,request)
	return HttpResponse(html)

##-------- Ajax --------
def getChaptcha(request):
	'''
	获取验证码
	'''
	img = captcha()
	img.gen_img()
	request.session["verifycode"] = img.strs
	buf = StringIO.StringIO()
	img.img.save(buf,'gif')
	return HttpResponse(buf.getvalue(),'image/gif')

def ChapchaMatch(getChaptcha,request):
	sessionChaptch = request.session["verifycode"]
	if getChaptcha.lower() == sessionChaptch.lower():
		return True
	else:
		return False

def checkChapcha(request):
	getChaptcha = request.POST.get("chapcha","").strip()
	context = {}
	context["match"] = ChapchaMatch(getChaptcha,request)
	return JsonResponse(context)

def unameAvailableCheck(request):
	'''
	检查注册新用户的用户名是否可用
	'''
	context = {}
	getUsername = request.POST.get('username')
	user_obj = User.objects.filter(username = getUsername)
	if user_obj:
		context['success'] = True
	else:
		context['success'] = False
	return JsonResponse(context)

def postRegister(request):
	'''
	提交注册信息
	'''
	userform = UserForm(request)
	context = {}

	if userform.is_valid():
		user = userform.save()
		try:
			user.sendMail("register")
		except:
			user.delete()
			context["success"] = False
			context["error"] = "send email failed !"
		else:
			setSession(request,user)
			context["success"] = True
	else:
		context["success"] = False
		context["error"] = userform.error
	return JsonResponse(context)

def postLogin(request):
	'''
	提交登陆信息
	'''
	username = request.POST.get("username","").strip()
	password = request.POST.get("password","").strip()
	chapcha = request.POST.get("validcode","").strip()
	context = {}

	chapcha_match = ChapchaMatch(chapcha,request)

	try:
		user = User.objects.get(username = username)
	except User.DoesNotExist:
		context["status"] = 0
	else:
		if user.active:
			if user.check_password(password):
				context["status"] = 1
			else:
				context["status"] = 0
		else:
			context["status"] = 2
	return JsonResponse(context)

website/users/views.py
#coding=utf-8

from django.template.loader import get_template
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse

from main.models import Category
from users.forms import userForm
from users.models import *
from users.functions import *

def login_required(func):
    def _login_required(request):
        if not getSession(request).is_login:
            context = {
                "type":"non_login",
                }
            template = get_template("user/information.html")
            html = template.render(context,request)
            return HttpResponse(html)
        else:
            return func(request)
    return _login_required

def Login(request):
    '''
    显示登陆页面
    '''
    catList = Category.objects.order_by('id')
    context = {
        'cat_list':catList,
        }
    template = get_template("user/login.html")
    html = template.render(context,request)
    return HttpResponse(html)

def Logout(request):
    '''
    登出
    '''
    delSession(request)
    return HttpResponseRedirect("/bbs/")

def Register(request):
    '''
    显示注册页面
    '''
    catList = Category.objects.order_by('id')
    context = {
        'cat_list':catList,
        }
    template = get_template("user/register.html")
    html = template.render(context,request)
    return HttpResponse(html)

def userActive(request):
    '''
    账户激活
    '''
    email_token = str(request.GET.get('token','').strip())
    catList = Category.objects.order_by('id')
    result = "success"
    context = {}
    context["type"] = "active"
    context["cat_list"] = catList

    try:
        user = User.objects.get(token=email_token)
    except:
        context["get_token"] = False
    else:
        context["get_token"] = True
        if user.active:
            context["info"] = u"该账户已激活"
        else:
            user.set_active()
            context["info"] = u"账户激活成功"
    template = get_template("user/information.html")
    html = template.render(context,request)
    return HttpResponse(html)

##-------- Ajax --------
def getChaptcha(request):
    '''
    获取验证码
    '''
    img = captcha()
    img.gen_img()
    request.session["verifycode"] = img.strs
    buf = StringIO.StringIO()
    img.img.save(buf,'gif')
    return HttpResponse(buf.getvalue(),'image/gif')

def ChapchaMatch(getChaptcha,request):
    sessionChaptch = request.session["verifycode"]
    if getChaptcha.lower() == sessionChaptch.lower():
        return True
    else:
        return False

def checkChapcha(request):
    getChaptcha = request.POST.get("chapcha","").strip()
    context = {}
    context["match"] = ChapchaMatch(getChaptcha,request)
    return JsonResponse(context)

def unameAvailableCheck(request):
    '''
    检查注册新用户的用户名是否可用
    '''
    context = {}
    getusername = request.POST.get('username')
    user_obj = User.objects.filter(username = getusername)
    if user_obj:
        context['success'] = True
    else:
        context['success'] = False
    return JsonResponse(context)

def postRegister(request):
    '''
    提交注册信息
    '''
    userform = userForm(request)
    context = {}

    if userform.is_valid():
        user = userform.save()
        try:
            user.sendMail("register")
        except:
            user.delete()
            context["success"] = False
            context["error"] = "send email failed !"
        else:
            setSession(request,user)
            context["success"] = True
    else:
        context["success"] = False
        context["error"] = userform.error
    return JsonResponse(context)

def postLogin(request):
    '''
    提交登陆信息
    '''
    username = request.POST.get("username","").strip()
    password = request.POST.get("password","").strip()
    chapcha = request.POST.get("validcode","").strip()
    context = {}

    chapcha_match = ChapchaMatch(chapcha,request)

    try:
        user = User.objects.get(username = username)
    except User.DoesNotExist:
        context["status"] = 0
    else:
        if user.active:
            if user.check_password(password):
                context["status"] = 1
                setSession(request,user)
            else:
                context["status"] = 0
        else:
            context["status"] = 2
    return JsonResponse(context)

templates/user/active.html
{% extends 'main/base.html' %}
{% block page-content %}
	{% if get_token %}
    <h3>{{ info }}，请<a href="/bbs/user/login/">登录</a></h3>
	{% else %}
	<h3>邮箱验证失败，请重试或联系管理员</h3>
	{% endif %}
{% endblock %}

templates/user/base.html
{% load static %}

<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <title>Chouti</title>
    <link type="text/css" rel="stylesheet" href={% static "pub/css/bootstrap.min.css" %}>
    <style>
    html {overflow-y: scroll;} 
    .shadow{
        padding:15px 30px;border:#909090 1px solid;background:#fff;color:#333;
        filter:progid:DXImageTransform.Microsoft.Shadow(color=#909090,direction=120,strength=4);/*ie*/
        -moz-box-shadow: 2px 2px 10px #909090;/*firefox*/
        -webkit-box-shadow: 2px 2px 10px #909090;/*safira & chrome*/
        box-shadow:2px 2px 10px #909090;/*opera ie9*/
    </style>
    {% block css %}
    {% endblock %}
</head>
<body>
    <div class="container">
        <!-- nav header -->
        <nav class="navbar navbar-default navbar-inverse" role="navigation">
            <div class="navbar-header">
                <a class="navbar-brand" href="/bbs">Chouti</a>
            </div>
            {% block navbar %}
            <ul class="nav navbar-nav navbar-left">
                {% for cat in cat_list  %}
                <li><a href=/bbs/{{ cat.name }}/>{{ cat.chinese_name }}</a></li>
                {% endfor %}
            </ul>
            {% endblock %}
            <ul class="nav navbar-nav navbar-right" style="margin-right:20px">
            {% if user.is_login %}
                <li><p class="navbar-text">欢迎</p></li>
                <li><a href="/bbs/Uinfo/{{ user.username }}/">{{user.username}}</a></li>
                <li><a href="/bbs/user/logout/">登出</a></li>
            {% else %}
                <li><a href="/bbs/user/login/">登陆</a></li>
                <li><a href="/bbs/user/register/">注册</a></li>
            {% endif %}
            </ul>
        </nav>
        <!-- body -->
        <div class="shadow col-md-12">
            {% block page-content %}
            {% endblock %}
        </div>
    </div>
    <script type="text/javascript" src={% static "pub/js/jquery.min.js" %}></script>
    <script type="text/javascript" src={% static "pub/js/bootstrap.min.js" %}></script>
    <script type="text/javascript" src={% static "bbs/js/csrf_token.js" %}></script>
    {% block js %}
    {% endblock %}
</body>
</html>

templates/user/infomation.html
{% extends 'user/base.html' %}

{% block page-content %}
    {% if type == "non_login" %}
        <p>请先<a href="/bbs/user/login/">登录</a>在查看用户信息！没有账号，请先<a href="/bbs/user/register/">注册</a></p>
    {% else type == "active" %}
    	{% if get_token %}
            <h3>{{ msg }}，请<a href="/bbs/user/login/">登录</a></h3>
        {% else %}
            <h3>邮箱验证失败，请重试或联系管理员</h3>
        {% endif %}
    {% endif %}
{% endblock %}

templates/user/register.html
{% extends 'user/base.html' %}

{% block page-content %}
	<div class="col-md-12" id="reg_container">
		<form class="form-horizontal  form-signin" role="form" " enctype="multipart/form-data">
		{% csrf_token %}
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<h2 class="col-sm-4" align="center"><strong>新用户注册</strong></h2>
				</div>
				<label for="inputname" class="col-sm-2 control-label">用户名</label>
				<div class="col-sm-4" >
					<input name="username" class="form-control" id="id_username"/>
				</div>
				<div class="col-sm-6">
					<p class="form-control-static" id="msg1"></p>
				</div>
				<div class="col-sm-12">
					<label class="col-sm-offset-2 col-sm-4"><b id="count" style="visibility:hidden">0个字符</b></label>
				</div>
					<div style='height:10px;clear:both;display:block'></div>
				<label for="inputphoto" class="col-sm-2 control-label">头像</label>
				<div class="col-sm-4" >
					<input type="file" id="id_photo" name="photo" class="col-sm-8"/>
				</div>
					<div style='height:10px;clear:both;display:block'></div>
				<label for="inputemail" class="col-sm-2 control-label">邮箱</label>
				<div class="col-sm-4" >
					<input type="text" id="id_email" name="email" class="form-control"/>
				</div>
				<div class="col-sm-6">
					<p class="form-control-static" id="msg2"></p>
				</div>
					<div style='height:10px;clear:both;display:block'></div>
				<label for="inputNewpassword" class="col-sm-2 control-label">密码</label>
				<div class="col-sm-4" >
					<input type="password" id="id_password1" name="password1" class="form-control"/>
				</div>
				<div class="col-sm-6">
					<p class="form-control-static" id="msg3"></p>
				</div>
				<div class="col-sm-12" style="margin-top:5px">
					<label class="col-sm-offset-2 col-sm-4"><span></span>
						<span class="label label-success" id="barge1">弱</span>
						<span class="label label-success" id="barge2">中</span>
						<span class="label label-success" id="barge3">强</span>
				</div>
					<div style='height:10px;clear:both;display:block'></div>
				<label for="reCheckNewPasswd" class="col-sm-2 control-label">确认密码</label>
				<div class="col-sm-4" >
					<input type="password" id="id_password2" name="password2" class="form-control"/>
				</div>
				<div class="col-sm-6">
					<p class="form-control-static" id="msg4"></p>
				</div>
					<div style='height:10px;clear:both;display:block'></div>
				<label for="CheckNewPasswd" class="col-sm-2 control-label">签名</label>
				<div class="col-sm-4" >
					<textarea id="id_signature" name="signature" class="form-control" >这家伙太懒，啥也没留下~</textarea>
				</div>
					<div style='height:10px;clear:both;display:block'></div>
				<div class="col-sm-offset-2 col-sm-10">
					<button class="btn btn-success btn-lg col-sm-4" id="sub_bt" type="button"/>注册</button>
				</div>
			</div>
		</form> 
	</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
 //获取键盘的enter动作
 	$(document).keyup(function(event){
		if(event.keyCode == 13){
			$("#sub_bt").trigger("click");
		}
	});

//获取字符串长度
function getLength(str){
	return str.replace(/[^\x00-xff]/g,'xx').length;
}

//检查字符串是否为一个字符
function findStr(str,n){
	var tmp=0;
	for(i=0;i<str.length;i++){
		if(str[i]==n){
			tmp++;
		}
	}
	return tmp;
}

//使用ajax检查用户名是否可用
function CheckUsername(str){
	var success;
	$.ajax({
		type:"post",
		dataType:"json",
		url:"/bbs/user/uname_available/",
		async:false,
		data:{ 
			"username":str,     
			}, 
		success: function (data) { 
				success = data.success;
			}				
		});
	return success;
	}
	
$(function(){

	var Uname=$("#id_username");
	var Upwd1=$("#id_password1");
	var Upwd2=$("#id_password2");
	var Uemail=$("#id_email");
	var name_msg=$("#msg1");
	var email_msg=$("#msg2");
	var pwd1_msg=$("#msg3");
	var pwd2_msg=$("#msg4");
	var barge1=$("#barge1");
	var barge2=$("#barge2");
	var barge3=$("#barge3");
	var count=$("#count")
	var name_length=0;
	var check_stat=0;
	var re=/[^\w\u4e00-\u9fa5]/g;

//username	
	Uname.focus(function(){
		name_msg.css('color','black');
		name_msg.html('<span class="glyphicon glyphicon-info-sign"></span>&nbsp;用户名可以使用字母、数字、下划线、汉字');
	});
	Uname.keyup(function(){
		count.css('visibility','visible');
		name_length=getLength(this.value);
		count.text(name_length+"个字符");
		if(name_length==0){
			count.css('visibility','hidden');
		}
	});
	Uname.blur(function(){
		name_length=getLength(this.value);
		var re1=/[^\w\u4e00-\u9fa5]/g;
		if(re1.test(this.value)){
			name_msg.html("<span class='glyphicon glyphicon-warning-sign'></span>&nbsp;含有非法字符");
		}
		else if(this.value==""){
			name_msg.html("<span class='glyphicon glyphicon-warning-sign'></span>&nbsp;用户名不能为空");
			}
		else if(name_length<6||name_length>20){
			name_msg.html("<span class='glyphicon glyphicon-warning-sign'></span>&nbsp;字符个数为6-20个");
		}
		else if(CheckUsername(this.value)){
			name_msg.html("<span class='glyphicon glyphicon-warning-sign'></span>&nbsp;用户名已使用！");
		}
		else{
			name_msg.html("<span class='glyphicon glyphicon-ok-sign'></span>&nbsp;OK");
		}
	});
	
//email
	Uemail.focus(function(){
		email_msg.css('color','black');
		email_msg.html('<span class="glyphicon glyphicon-info-sign"></span>&nbsp;支持各主流邮箱，必填项');
	});
	
	Uemail.blur(function(){
		var re2=/^[a-zA-Z0-9_]{3,15}@[a-zA-Z0-9]{2,10}\.[a-z]{2,3}$/g;
		if(this.value==""){
			email_msg.html("<span class='glyphicon glyphicon-warning-sign'></span>&nbsp;邮箱不能为空");
		}
		else if(!re2.test(this.value)){
			email_msg.html("<span class='glyphicon glyphicon-warning-sign'></span>&nbsp;邮箱格式非法");
		}
		else{
			email_msg.html("<span class='glyphicon glyphicon-ok-sign'></span>&nbsp;OK");
		}
	});
	
//password1

	Upwd1.focus(function(){
		pwd1_msg.css('color','black');
		Upwd2.removeAttr("disabled");
		pwd1_msg.html('<span class="glyphicon glyphicon-info-sign"></span>&nbsp;6-16个字符，不能单独使用字母、数字，请组合使用');
	});
	Upwd1.keyup(function(){
		if(this.value.length>6){
			barge1.removeClass("label-danger");
			barge1.addClass("label-success");
			barge2.removeClass("label-success");
			barge2.addClass("label-danger");
			pwd2_msg.show();
			pwd2_msg.html('<span class="glyphicon glyphicon-info-sign"></span>&nbsp;请再次输入密码');	
		}
		else{
			barge1.removeClass("label-success");
			barge1.addClass("label-danger");
			barge2.removeClass("label-danger");
			barge2.addClass("label label-success");
			pwd2_msg.hide();
		}
		if(this.value.length>10){
			barge2.removeClass("label-danger");
			barge2.addClass("label-success");
			barge3.removeClass("label-success");
			barge3.addClass("label-danger");
		}
		else{
			barge3.removeClass("label-danger");
			barge3.addClass("label-success");
		}
	});
	Upwd1.blur(function(){
		pwd2_msg.hide();
		Upwd2.attr("disabled",true);
		var samestr=findStr(this.value,this.value[0])
		var re_d=/[^\d+]/g;
		var re_l=/[^a-zA-Z]/g;
		if(this.value==""){
			pwd1_msg.html('<span class="glyphicon glyphicon-warning-sign"></span>&nbsp;不能为空');
		}
		else if(!re_d.test(this.value)){
			pwd1_msg.html('<span class="glyphicon glyphicon-warning-sign"></span>&nbsp;不能全为数字');
		}
		else if(!re_l.test(this.value)){
			pwd1_msg.html('<span class="glyphicon glyphicon-warning-sign"></span>&nbsp;不能全为字母');
		}
		else if(this.value.length<6||this.value.length>16){
			pwd1_msg.html('<span class="glyphicon glyphicon-warning-sign"></span>&nbsp;长度必须为6-16个字符');
		}
		else if(this.value.length==samestr){
			pwd1_msg.html('<span class="glyphicon glyphicon-warning-sign"></span>&nbsp;密码不能为相同字符');
		}
		else{
			pwd2_msg.show();
			pwd2_msg.html('<span class="glyphicon glyphicon-info-sign"></span>&nbsp;请再次输入密码');
			pwd1_msg.html('<span class="glyphicon glyphicon-ok-sign"></span>&nbsp;OK');
			Upwd2.removeAttr("disabled");
		}
	});

//password2
		Upwd2.focus(function(){
			pwd2_msg.css("color","black");
			pwd2_msg.html('<span class="glyphicon glyphicon-info-sign"></span>&nbsp;请再次输入密码');
		});
		Upwd2.blur(function(){
			if(this.value==""){
				pwd2_msg.html('<span class="glyphicon glyphicon-warning-sign"></span>&nbsp;密码不能为空');
			}
			else if(this.value!=Upwd1.val()){
				pwd2_msg.html('<span class="glyphicon glyphicon-warning-sign"></span>&nbsp;两次输入的密码不匹配');
			}
			else{
				pwd2_msg.html('<span class="glyphicon glyphicon-ok-sign"></span>&nbsp;OK');
			}
		});
		
//注册项校验结束

	$("#sub_bt").bind("click",function(){
	
		Uname.trigger("blur");
		Uemail.trigger("blur");
		Upwd1.trigger("blur");
		Upwd2.trigger("blur");
		
		var get_check=$("p:contains('OK')").length;
		var warn_item=$(".glyphicon-warning-sign").parent();
		
		//确认各校验项已注册通过
		warn_item.each(function(){
			$(this).css("color","red");
		});
	
		//ajax提交注册信息
		if(get_check==4){
			$.ajax({
				type:"post",
				dataType:"json",
				url:"/bbs/user/post_register/",
				data:{ 
					"username":Uname.val(),
					"password":Upwd2.val(),
					"email":Uemail.val(),
					"signature":$("#signature").val(),
					}, 
				success: function (data) { 
						if(data.success){
							var html="<h3 align='center'>注册成功&nbsp;请登录邮箱查看验证邮件</a></h3>"
							$("#reg_container").html(html);
						}
						else{
							var html="<h3 align='center'>注册失败，请刷新页面重试！</a></h3>"
							$("#reg_container").html(html);
						}
					}				
			});
		
		
		}
	});

});
</script>
{% endblock %}